<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpxabI3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpxabI3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXpxabI3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXpxabI3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXpxabI3\App_KernelDevDebugContainer([
    'container.build_hash' => 'XpxabI3',
    'container.build_id' => '367f9a60',
    'container.build_time' => 1617977975,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpxabI3');
