<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEqhN2TQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEqhN2TQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEqhN2TQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEqhN2TQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEqhN2TQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'EqhN2TQ',
    'container.build_id' => '1a010524',
    'container.build_time' => 1617810921,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEqhN2TQ');
