<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSyNwgHB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSyNwgHB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSyNwgHB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSyNwgHB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSyNwgHB\App_KernelDevDebugContainer([
    'container.build_hash' => 'SyNwgHB',
    'container.build_id' => '85b18ee3',
    'container.build_time' => 1617526426,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSyNwgHB');
